name: "node.js check"
on: [push]
jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.13.0'
      - name: Run
        run: npx is-my-node-vulnerable
  is-my-dep-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.13.0'
      - name: Run
        run: npm audit
